import mcp.types as types
import json
from powerbi.model_reader import ModelReader

SCHEMA = types.Tool(
    name="inspect_table",
    description=(
        "Inspect a table holistically, returning its name, physical columns, calculated columns "
        "with their DAX expressions, and sample rows. This is the main table-understanding tool. "
        "Supports automatic instance binding if only one Power BI Desktop instance is running. "
        "Accepts an optional 'port' argument to query a specific instance directly."
    ),
    inputSchema={
        "type": "object",
        "properties": {
            "table": {
                "type": "string",
                "description": "Name of the table to inspect. Optional if only one business-relevant table exists."
            },
            "limit": {
                "type": "integer",
                "description": "Maximum number of sample rows to preview. Default is 5."
            },
            "port": {
                "type": "integer",
                "description": "Optional port of a specific running Power BI Desktop instance to query."
            }
        }
    }
)

async def execute(arguments: dict, connection) -> list[types.TextContent]:
    reader = ModelReader(connection)
    try:
        resolved_table = await reader.resolve_table_name(arguments.get("table"))
        limit = arguments.get("limit", 5)
        
        # 1. Fetch columns metadata
        columns = await reader.get_table_columns(resolved_table)
        
        # 2. Fetch sample rows
        try:
            rows = await reader.preview_table_data(resolved_table, limit)
        except Exception as data_err:
            rows = []
            row_preview_error = str(data_err)
        else:
            row_preview_error = None
            
        physical_cols = []
        calculated_cols = []
        for col in columns:
            col_info = {
                "name": col["name"],
                "data_type": col["data_type"],
                "is_hidden": col["is_hidden"],
                "description": col["description"]
            }
            if col["kind"] == "physical":
                if col["source"]:
                    col_info["source"] = col["source"]
                physical_cols.append(col_info)
            elif col["kind"] == "calculated":
                col_info["dax_expression"] = col["dax_expression"]
                calculated_cols.append(col_info)
        
        output = []
        output.append(f"# Table Inspection: {resolved_table}")
        output.append("")
        
        notes = []
        if resolved_table.startswith("LocalDateTable_") or resolved_table.startswith("DateTableTemplate_") or "LocalDateTable" in resolved_table or "DateTableTemplate" in resolved_table:
            notes.append("- Note: This table appears to be an internal autogenerated/technical date table.")
        if not physical_cols and calculated_cols:
            notes.append("- Note: This table contains only calculated columns; it may be a calculated table or a helper table.")
        if notes:
            output.append("## Notes")
            output.extend(notes)
            output.append("")
            
        output.append("## Physical / Original Columns")
        if physical_cols:
            for col in physical_cols:
                desc = f" - {col['description']}" if col['description'] else ""
                hidden_str = " (Hidden)" if col['is_hidden'] else ""
                source_str = f" [Source: {col['source']}]" if col.get('source') else ""
                output.append(f"* **{col['name']}** ({col['data_type']}){hidden_str}{source_str}{desc}")
        else:
            output.append("*No physical columns found.*")
        output.append("")
        
        output.append("## Calculated Columns")
        if calculated_cols:
            for col in calculated_cols:
                desc = f" - {col['description']}" if col['description'] else ""
                hidden_str = " (Hidden)" if col['is_hidden'] else ""
                output.append(f"* **{col['name']}** ({col['data_type']}){hidden_str}{desc}")
                output.append("  DAX Expression:")
                output.append("  ```dax")
                output.append(col['dax_expression'])
                output.append("  ```")
        else:
            output.append("*No calculated columns found.*")
        output.append("")
        
        output.append("## Sample Data Preview")
        if row_preview_error:
            output.append(f"*Error loading sample data preview: {row_preview_error}*")
        elif rows:
            output.append(f"Showing up to {limit} sample rows:")
            output.append("```json")
            output.append(json.dumps(rows, indent=2, ensure_ascii=False))
            output.append("```")
        else:
            output.append("*Table is empty or returned no rows.*")
            
        return [types.TextContent(type="text", text="\n".join(output))]
    except Exception as e:
        return [types.TextContent(type="text", text=f"Error inspecting table: {str(e)}")]
